### PR TITLE
Added text box for user email address. added email_address in create …

### PR DESCRIPTION
**Pull request by eoliveros**
…invoice. status is still optional.

### CODE REVIEW

**Comment by djpnewton** [comment]
erick can you test these changes and let me know how it goes

**Comment by eoliveros** [comment]
will need to wait... the deployment is failing like with the gevent stuff. When it happens i have to wait for the load on the server to go down again.

**Comment by eoliveros** [comment]
deployed but there's an authentication thats needed when submitting payment. cant proceed further.

**Comment by eoliveros** [comment]
deployed and been getting the update notification email:
image


Not sure where I could change the email address though. Coming up as localhost.

Also the timing on the above example may have taken closer to 30 minutes for the email to be received?
image



Otherwise the notification seems to work.

**Comment by eoliveros** [comment]
ahh nah, it looks like i received an email at 1pm. The other notification must be when it expired.

**Comment by djpnewton** [comment]
looks good lets try it on heroku

**Pull request merged**
